using UnityEngine;
[CreateAssetMenu(fileName = "EnemyOnHitCategory", menuName = "Data/EnemyOnHitCategory")]
public class EnemyOnHitCategory : GalleryCategory {

    [HideInInspector] public AudioClip EnemyOnHit;
    [HideInInspector] public AudioClip Enemy09OnHit;
    [HideInInspector] public AudioClip EnemyAZOnHit;
    [HideInInspector] public AudioClip BigEnemyOnHit;
    [HideInInspector] public AudioClip ColoredEnemyOnHit;
    [HideInInspector] public AudioClip EnemyAssasinAssaultOnHit;
    [HideInInspector] public AudioClip EnemyAssasinBigOnHit;
    [HideInInspector] public AudioClip EnemyAssasinBungeeOnHit;
    [HideInInspector] public AudioClip EnemyAssasinTowerOnHit;
    [HideInInspector] public AudioClip EnemyBombOnHit;
    [HideInInspector] public AudioClip EnemyShooterOnHit;
    [HideInInspector] public AudioClip EnemySwarmOnHit;
    [HideInInspector] public AudioClip EnemySwarmSpawnerOnHit;
    [HideInInspector] public AudioClip GoldenSnitchBossOnHit;

    public Sprite EnemyOnHitIcon;
    public Sprite Enemy09OnHitIcon;
    public Sprite EnemyAZOnHitIcon;
    public Sprite BigEnemyOnHitIcon;
    public Sprite ColoredEnemyOnHitIcon;
    public Sprite EnemyAssasinAssaultOnHitIcon;
    public Sprite EnemyAssasinBigOnHitIcon;
    public Sprite EnemyAssasinBungeeOnHitIcon;
    public Sprite EnemyAssasinTowerOnHitIcon;
    public Sprite EnemyBombOnHitIcon;
    public Sprite EnemyShooterOnHitIcon;
    public Sprite EnemySwarmOnHitIcon;
    public Sprite EnemySwarmSpawnerOnHitIcon;
    public Sprite GoldenSnitchBossOnHitIcon;
    //public AudioClip attack1;
    //public AudioClip attack2;
    //public AudioClip attack3;
    //public AudioClip attack4;
    //public AudioClip attack5;
    //public AudioClip attack6;
    //public AudioClip attack7;
    //public AudioClip attack8;
    //public AudioClip attack9;
    //public AudioClip attack10;
    //public AudioClip attack11;
    //public AudioClip attack12;
    //public AudioClip attack13;
    //public AudioClip attack14;
    //public AudioClip attack15;
    //public AudioClip attack16;
    //public AudioClip attack17;
    //public AudioClip attack18;
    //public AudioClip attack19;
    //public AudioClip attack20;
    //public AudioClip attack21;
    //public AudioClip attack22;
    //public AudioClip attack23;
    //public AudioClip attack24;
    //public AudioClip attack25;
    //public AudioClip attack26;
    //public AudioClip attack27;
    //public AudioClip attack28;
    //public AudioClip attack29;
    //public AudioClip attack30;
    //public AudioClip attack31;
    //public AudioClip attack32;
    //public AudioClip attack33;
    //public AudioClip attack34;
    //public AudioClip attack35;
    //public AudioClip attack36;
    //public AudioClip attack37;
    //public AudioClip attack38;
    //public AudioClip attack39;
    //public AudioClip attack40;
    //public AudioClip attack41;
    //public AudioClip attack42;
    //public AudioClip attack43;
    //public AudioClip attack44;
    //public AudioClip attack45;
    //public AudioClip attack46;
    //public AudioClip attack47;
    //public AudioClip attack48;
    //public AudioClip attack49;
    //public AudioClip attack50;
    //public AudioClip attack51;
    //public AudioClip attack52;
    //public AudioClip attack53;
    //public AudioClip attack54;
    //public AudioClip attack55;
    //public AudioClip attack56;
    //public AudioClip attack57;
    //public AudioClip attack58;
    //public AudioClip attack59;
    //public AudioClip attack60;
    //public AudioClip attack61;
    //public AudioClip attack62;
    //public AudioClip attack63;
    //public AudioClip attack64;
    //public AudioClip attack65;
    //public AudioClip attack66;
    //public AudioClip attack67;
    //public AudioClip attack68;
    //public AudioClip attack69;
    //public AudioClip attack70;



}
